version: '3.7'

services:
  goronime:
    container_name: goronime_fe
    image: goronime
    build:
      context: .
    env_file: ".env"
    volumes:
       - '.:/app'
       - /app/node_modules/ 
    ports:
      - "${PORT_APP}:4173"